services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
    - RabbitMqUser=guest
    - RabbitMqPassword=guest
    - RabbitMqVhost=/
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 10s
        retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FamilyDb
    ports:
       - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  family.api:
    build:
      context: ../../
      dockerfile: src/Family.API/Dockerfile
    container_name: family-api
    depends_on:
       rabbitmq:
         condition: service_healthy

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=FamilyDb;Username=postgres;Password=postgres
      - RabbitMqHost=rabbitmq
      - RabbitMqPort=5672
      - RabbitMqUser=guest
      - RabbitMqPassword=guest
    ports:
      - "8880:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge  