services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
    - RabbitMqUser=guest
    - RabbitMqPassword=guest
    - RabbitMqVhost=/
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - app-network
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 30s
        retries: 5
    restart: always

  family.postgres:
    image: postgres:15-alpine
    container_name: postgres.family
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FamilyDb
    ports:
       - "5433:5432"
    volumes:
      - family_pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d FamilyDb"]
        interval: 30s
        retries: 5
    networks:
      - app-network

  wallet.postgres:
    image: postgres:15-alpine
    container_name: postgres.wallet
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WalletDb
    ports:
      - "5434:5432"
    volumes:
      - wallet_pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d WalletDb"]
        interval: 30s
        retries: 5
    networks:
      - app-network

  expences.postgres:
    image: postgres:15-alpine
    container_name: postgres.expences
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ExpencesDb
    ports:
      - "5435:5432"
    volumes:
      - expences_pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d ExpencesDb"]
        interval: 30s
        retries: 5
    networks:
      - app-network

  family.api:
    build:
        context: ../../
        dockerfile: src/Family.API/Dockerfile
    container_name: api.family
    depends_on:
        rabbitmq:
            condition: service_healthy
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - CONNECTION_STRING=Host=family.postgres;Port=5432;Database=FamilyDb;Username=postgres;Password=postgres
        - RabbitMqHost=rabbitmq
        - RabbitMqPort=5672
        - RabbitMqUser=guest
        - RabbitMqPassword=guest
    ports:
        - "8880:80"
    networks:
        - app-network

  wallet.api:
        image: wallet.api
        container_name: api.wallet
        build:
          context: ../../../Wallet
          dockerfile: Wallet.API/Dockerfile
        environment: 
        - CONNECTION_STRING=Host=wallet.postgres;Port=5432;Database=WalletDb;Username=postgres;Password=postgres
        - ASPNETCORE_ENVIRONMENT=Development
        ports:
          - "8881:81"
        depends_on:
          rabbitmq:
            condition: service_healthy
          wallet.postgres:
            condition: service_healthy 
        networks:
          - app-network
   
  expences.api:
    image: expences.api
    container_name: api.expences
    build:
        context: ../../../Expenses
        dockerfile: Expenses.API/Dockerfile
    environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - CONNECTION_STRING=Host=expences.postgres;Port=5432;Database=ExpencesDb;Username=postgres;Password=postgres
    ports:
        - "8882:82"
    depends_on:
        rabbitmq:
            condition: service_healthy
        expences.postgres:
            condition: service_healthy 
    networks:
        - app-network
        
volumes:
  family_pgdata:
  wallet_pgdata:
  expences_pgdata:

networks:
  app-network:
    driver: bridge  